### ISSUE TITLE
Inconsistent chunk_size while uploading tokio::fs::File

### ISSUE THREAD

**Issue by limoiie** [djedi23/mongodb-gridfs-rs#6]
Hi~ Thanks a lot for your work on this repo bridging the gap between gridfs and rust.

I run into a bug recently. The chunk_size shown in collection fs.files may be inconsistent with collection fs.chunks.

## Describe the bug
The logic of method `upload.rs:upload_from_stream` breaks down when I try to upload a `tokio::fs::File`. After uploading a `tokio::fs::File` with default chunk_size 261120, the chunk sizes shown in documents in collection fs.files are correct, but the real size of each chunk stored in collection fs.chunks is nevertheless 16384.

After debugging I found that the method `tokio::fs::File::read` only reads 16384 bytes on each call, which cannot fulfill the chunk buffer with chunk_size bigger than 16384.

## Reproduce the bug
After adding cases of uploading `tokio::fs::File`, the failure information of the testing demonstrates the bug.
Please see [here](https://github.com/limoiie/mongodb-gridfs-rs/actions/runs/4159599691/jobs/7195800476#logs) for the testing details.

I run into this bug when uploading `tokio::fs::File`, but I believe this bug also appears when the system io is in busy or the hardware io resource is limited, where not every call of method `read` would fill the given buffer.

## Possible simple fixes
Loop the reading until either fulfilling the chunk buffer or reaching the file end

**Comment by djedi23** [comment]
Fixed in version 0.2.4 by PR #8 .
