### ISSUE TITLE
is it possible to get  all files in an fs collection using this library? if so how

### ISSUE THREAD

**Issue by veritem** [djedi23/mongodb-gridfs-rs#9]
All examples show how to get one file, I feel like there is a way of all files in a collection but I can't figure out how.

**Comment by veritem** [comment]
This is dump, I literally forgot `.find(None, GridFSFindOptions::default())` exists

**Comment by djedi23** [comment]
Hi,

No problem. It happens to everyone.

If the issue weren't solved, I'd point you on this example: https://github.com/djedi23/mongodb-gridfs-rs/blob/master/examples/find.rs
